# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - dynamodb-local
            - dynamodb-admin
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    dynamodb-local:
        image: amazon/dynamodb-local:latest
        user: root
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
        volumes:
          - dynamodb-local-data:/data
        ports:
          - 8000:8000
        networks:
          - sail 
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin:latest
        environment:
          - DYNAMO_ENDPOINT=dynamodb-local:8000
        ports:
          - 8001:8001
        depends_on:
          - dynamodb-local
        networks:
          - sail 
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    dynamodb-local-data:
        driver: local

